# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
# relative_permalinks: true

# Setup
title:               code /r/n stuff
tagline:             'What a world?'
description:         'Drinks coffee and makes things happen'
url:                 http://manujiththecoder.me
baseurl:             '/blog'
paginate:            5

# About/contact
author:
  name:              Manujith Pallewatte
  url:               https://twitter.com/_manzzup_
  email:             manujith.nc@gmail.com

# Custom vars
version:             1.0.0
