# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
# relative_permalinks: true

# Setup
title:               codes /r/n stuffs
tagline:             'What a world?'
description:         'Drinks coffee and makes things happen'
url:                 http://blog.manujiththecoder.me
baseurl:             '/test'
paginate:            5

# About/contact
author:
  name:              Manujith Pallewatte
  url:               https://twitter.com/_manzzup_
  email:             manujith.nc@gmail.com

github:
  repo:              http://github.com/manzzup

# Custom vars
version:             1.0.0

plugins: [jekyll-paginate]
